### ISSUE TITLE
Hero Pawn doesnt render properly in split screen multiplayer

### ISSUE THREAD

**Issue by setzer6127** [tranek/GASShooter#6] opened 2020-04-22 02:38 UTC
So i have been using this project as a bases to learn the ability system and when i tried to implement split screen multiplayer i ran into an odd problem. The Hero character acts like all the players are the owner of the Hero character and will only show the first person arms and gun, BUT The body is still shootable even though it doesnt render. 

If you change PIE to use multiple windows and do multiplayer that way it works fine. 

I've been working through the HeroCharacter code, and the player base class code but i'm not really figuring it out. if you do the normal Show only to owner on the first person and show to everyone else on the 3rd person mesh, nothing shows up, just a gun floating there. 

Any Thoughts? insights? recommendations?

**Comment by tranek** [comment] 2020-04-22 13:58
I haven't worked with split screen multiplayer and this project does not support it. Unfortunately I cannot help you since I don't know. Since it's not a bug in the project because it's not a supported feature, I'm closing this issue.

**Closed as completed by tranek** 2020-04-22 13:58 UTC

**Comment by setzer6127** [comment] 2020-04-24 00:24
Just incase anyone else comes here looking for answers for this problem. 

I solved it by removing the "3rd Person toggle" functions and anything to do with 3rd person. Then it showed the first person mesh on the owning player controller and the 3rd person mesh properly for all non-owning player controller windows in a split screen environment. I assume if you're looking for 3rd person view, doing the opposite will work as well.
